name: wra_data_sql
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
repository: https://github.com/regisaraujo/wra_data_sql.git

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.0.2
  postgres: ^3.4.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.5+3

  wra_core:
    git:
      url: https://github.com/regisaraujo/wra_core.git
  wra_core_data:
    git:
      url: https://github.com/regisaraujo/wra_core_data.git
  wra_domain_interface:
    git:
      url: https://github.com/regisaraujo/wra_domain_interface.git
  wra_entity_interface:
    git:
      url: https://github.com/regisaraujo/wra_entity_interface.git
  wra_repository_interface_sql:
    git:
      url: https://github.com/regisaraujo/wra_repository_interface_sql.git

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
